---
- name: Get interfaces from CLI
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Issue command
      nxos_command:
         commands: show ip interface brief
         provider:
               username: "{{ username }}"
               password: "{{ password }}"
               port: "{{ port }}"
               host: "{{ ansible_host }}"
               transport: "{{ transport }}"
               timeout: 30
               use_ssl: yes
               validate_certs: no
      register: interfaces
    - name: Print results
      debug:
         msg: 
            - "{{ interfaces.stdout[0] }}"
