---
- name: Get version from CLI
  hosts: csr
  gather_facts: no
  connection: local
  tasks:
    - name: Issue command
      ios_command:
         commands: show version
         provider:
               username: "{{ username }}"
               password: "{{ password }}"
               port: "{{ port }}"
               host: "{{ ansible_host }}"
               timeout: 30
      register: version
    - name: Print results
      debug:
         msg:
            - "{{ version.stdout[0] }}"
           #- "Vendor: {{ version.stdout[0].manufacturer }}"
           #- "Device: {{ version.stdout[0].chassis_id }}"
           #- "Hostname: {{ version.stdout[0].host_name }}"
           #- "Version: {{ version.stdout[0].nxos_ver_str }}"
