---
- name: Get version from facts
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Get hardware facts
      nxos_facts:
         gather_subset: hardware
         provider:
               username: "{{ username }}"
               password: "{{ password }}"
               port: "{{ port }}"
               host: "{{ ansible_host }}"
               transport: "{{ transport }}"
               timeout: 30
               use_ssl: yes
               validate_certs: no
      register: hardware
    - name: Print
      debug:
        msg: 
            - "Hostname: {{ ansible_net_hostname }}"
            - "Version: {{ ansible_net_version }}"

#ok: [nexus_sandbox] => {
#    "msg": {
#        "ansible_facts": {
#            "ansible_net_filesystems": [
#                "bootflash:"
#            ],
#            "ansible_net_gather_subset": [
#                "hardware",
#                "default"
#            ],
#            "ansible_net_hostname": "sbx-n9kv-ao",
#            "ansible_net_image": "bootflash:///nxos.9.3.3.bin",
#            "ansible_net_memfree_mb": 11955,
#            "ansible_net_memtotal_mb": 16024,
#            "ansible_net_model": "Nexus9000 C9300v Chassis",
#            "ansible_net_serialnum": "9N3KD63KWT0",
#            "ansible_net_version": "9.3(3)"
#        },
#        "changed": false,
#        "failed": false
#    }
#}

